config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'contact' => 'home#contact', as: :contact
  get 'faq' => 'home#faq', as: :faq

  root 'home#land'

    resources :tasks, except: [:show]
    resources :articles do
      resources :comments
    end

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  # has_many("comments", {:dependent => :destroy})
  validates :title, presence: true, length: { minimum:5 }
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  commenter  :string
#  body       :text
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  status      :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Task < ActiveRecord::Base
  module Status
    NOT_STARTED = 0
    STARTED = 1
    FINISHED = 2
  end

  scope :not_started, -> {where(status: Status::NOT_STARTED)}
  scope :started,     -> {where(status: Status::STARTED)}
  scope :finished,    -> {where(status: Status::FINISHED)}

  validates :title, presence: true

  def not_started?
    self.status == Status::NOT_STARTED
  end

  def started?
    self.status == Status::STARTED
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ArticlesController < ApplicationController

  # http_basic_authenticate_with name: "dhh", password: "secret",
  # except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:title,:text)
  end

end

app/controllers/comments_controller.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  commenter  :string
#  body       :text
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CommentsController < ApplicationController

  # http_basic_authenticate_with name: "dhh", password: "secret",
  # only: [:destroy]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comments = @article.comments.find(params[:id])
    @comments.destroy
    redirect_to article_path(@article)
  end

private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def land
  end

  def contact
  end

  def faq
  end
end

app/controllers/tasks_controller.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  status      :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class TasksController < ApplicationController
  def index
    @not_started_tasks = Task.not_started
    @started_tasks = Task.started
    @finished_tasks = Task.finished
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "Task created successfully"
      redirect_to tasks_path
    else
      flash.now[:error] = "Something went wrong. Please try again"
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attribute(:status, params[:status].to_i)
  end

private
  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module ArticlesHelper
end

app/helpers/comments_helper.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  commenter  :string
#  body       :text
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  status      :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error")%> prohibited this article from being saved.
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing Articles</h1>

<%= render 'form' %>

<% link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New Article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @article.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Back', articles_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>


<h2>Add a Comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
                                method: :delete,
                                data: { confirm: 'Are you sure?' }  %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<p>
  <%= f.label :commenter %>
  <%= f.text_field :commenter %>
</p>
<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/common/_header.html.erb
<nav>
  <%= link_to "Home", root_path %>
  <%= link_to "Blog", articles_path %>
  <%= link_to "FAQs", faq_path %>
  <%= link_to "Contact Us", contact_path %>
  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    (Logged in as: <%= current_user.email %>)
  <% else %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</nav>

app/views/home/contact.html.erb
<h1>Contact Us</h1>

app/views/home/faq.html.erb
<h1>FAQ</h1>

app/views/home/land.html.erb
<div id="land">
  <div class="vcenter">
    <h1>Welcome to the machine</h1>
    <%= link_to "Blog", articles_path %>
    <%= link_to "Contact", contact_path %>
    <%= link_to "Contact", contact_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if flash[:success] || flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:success] || flash[:notice] %></div>
  <% elsif flash[:error] || flash[:alert] %>
    <div class="alert alert-danger" role="alert"><%= flash[:error] || flash[:alert] %></div>
  <% end %>
  <%= render partial: 'common/header' unless controller_name == "home" && action_name == "land" %>
  <%= yield %>
</div>

</body>
</html>

app/views/tasks/_task.html.erb
<% if task.not_started? %>
<li>
  <%= task.title %>
  (<%= link_to "Start", task_path(task, status: Task::Status::STARTED), method: :patch, remote: true %>)
</li>
<% elsif task.started? %>
<li id="<%= dom_id(task) %>">
  <%= task.title %>
  (
  <%= link_to "Finish", task_path(task, status: Task::Status::FINISHED), method: :patch, remote: true %>
  |
  <%= link_to "Shelf", task_path(task, status: Task::Status::NOT_STARTED), method: :patch, remote: true %>
  )
</li>
<% else %>
<li>
  <%= task.title %>
  (<%= link_to "Rework", task_path(task, status: Task::Status::STARTED), method: :patch, remote: true %>)
</li>
<% end %>

app/views/tasks/index.html.erb
<h1>Not Started</h1>
<ul id="tasks-<%= Task::Status::NOT_STARTED %>">
  <%# @not_started_tasks.each do |task| %>
    <%#= render partial: 'tasks/task', locals: {task: task} %>
    <%#= render task %>
  <%# end %>
  <%= render @not_started_tasks %>
</ul>

<h1>Started Tasks</h1>
<ul id="tasks-<%= Task::Status::STARTED %>">
  <%= render @started_tasks %>
</ul>

<h1>Finished Tasks</h1>
<ul id="tasks-<%= Task::Status::FINISHED %>">
  <%= render @finished_tasks %>
</ul>

<%= link_to "Add New Task", new_task_path, class: "btn btn-primary btn-sm" %>

app/views/tasks/new.html.erb
<h1>Add new task</h1>

<%= form_for  @task do |t| %>

<p>
  <%= t.label :title %>
  <%= t.text_field :title %>
</p>

<p>
  <%= t.label :description %>
  <%= t.text_area :description %>
</p>

<p>
  <%= t.submit %>
</p>

<% end %>

app/views/tasks/update.js.erb
$('#<%= dom_id(@task) %>').remove();
$('ul#tasks-<%= @task.status %>').append('<%= j render(@task) %>');

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>